services:
  ielts:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ielts-app
    ports:
      - "8080:8080" # Change this if your app runs on a different port
    restart: unless-stopped
